/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UasgCodigoUasgRouteImport } from './routes/uasg.$codigoUasg'
import { Route as UasgCodigoUasgIndexRouteImport } from './routes/uasg.$codigoUasg.index'
import { Route as UasgCodigoUasgArpAtaRouteImport } from './routes/uasg.$codigoUasg.arp.$ata'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UasgCodigoUasgRoute = UasgCodigoUasgRouteImport.update({
  id: '/uasg/$codigoUasg',
  path: '/uasg/$codigoUasg',
  getParentRoute: () => rootRouteImport,
} as any)
const UasgCodigoUasgIndexRoute = UasgCodigoUasgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UasgCodigoUasgRoute,
} as any)
const UasgCodigoUasgArpAtaRoute = UasgCodigoUasgArpAtaRouteImport.update({
  id: '/arp/$ata',
  path: '/arp/$ata',
  getParentRoute: () => UasgCodigoUasgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/uasg/$codigoUasg': typeof UasgCodigoUasgRouteWithChildren
  '/uasg/$codigoUasg/': typeof UasgCodigoUasgIndexRoute
  '/uasg/$codigoUasg/arp/$ata': typeof UasgCodigoUasgArpAtaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/uasg/$codigoUasg': typeof UasgCodigoUasgIndexRoute
  '/uasg/$codigoUasg/arp/$ata': typeof UasgCodigoUasgArpAtaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/uasg/$codigoUasg': typeof UasgCodigoUasgRouteWithChildren
  '/uasg/$codigoUasg/': typeof UasgCodigoUasgIndexRoute
  '/uasg/$codigoUasg/arp/$ata': typeof UasgCodigoUasgArpAtaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/uasg/$codigoUasg'
    | '/uasg/$codigoUasg/'
    | '/uasg/$codigoUasg/arp/$ata'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/uasg/$codigoUasg' | '/uasg/$codigoUasg/arp/$ata'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/uasg/$codigoUasg'
    | '/uasg/$codigoUasg/'
    | '/uasg/$codigoUasg/arp/$ata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UasgCodigoUasgRoute: typeof UasgCodigoUasgRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uasg/$codigoUasg': {
      id: '/uasg/$codigoUasg'
      path: '/uasg/$codigoUasg'
      fullPath: '/uasg/$codigoUasg'
      preLoaderRoute: typeof UasgCodigoUasgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uasg/$codigoUasg/': {
      id: '/uasg/$codigoUasg/'
      path: '/'
      fullPath: '/uasg/$codigoUasg/'
      preLoaderRoute: typeof UasgCodigoUasgIndexRouteImport
      parentRoute: typeof UasgCodigoUasgRoute
    }
    '/uasg/$codigoUasg/arp/$ata': {
      id: '/uasg/$codigoUasg/arp/$ata'
      path: '/arp/$ata'
      fullPath: '/uasg/$codigoUasg/arp/$ata'
      preLoaderRoute: typeof UasgCodigoUasgArpAtaRouteImport
      parentRoute: typeof UasgCodigoUasgRoute
    }
  }
}

interface UasgCodigoUasgRouteChildren {
  UasgCodigoUasgIndexRoute: typeof UasgCodigoUasgIndexRoute
  UasgCodigoUasgArpAtaRoute: typeof UasgCodigoUasgArpAtaRoute
}

const UasgCodigoUasgRouteChildren: UasgCodigoUasgRouteChildren = {
  UasgCodigoUasgIndexRoute: UasgCodigoUasgIndexRoute,
  UasgCodigoUasgArpAtaRoute: UasgCodigoUasgArpAtaRoute,
}

const UasgCodigoUasgRouteWithChildren = UasgCodigoUasgRoute._addFileChildren(
  UasgCodigoUasgRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UasgCodigoUasgRoute: UasgCodigoUasgRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
